Settings, Explorer, My repo 번역 추가
hatemogi/github-ko-ext pull request #10
Opened 2021-08-09 04:33 UTC by mandoopapa

Settings와 Explorer, My Repositories 화면 내 일부 번역 작업 진행하였습니다.

별도의 번호와 주석으로 표시해두었습니다.

2021-08-09 05:08 UTC, hsh2001 requested changes

2021-08-09 05:08 UTC, hsh2001 commented on chrome/github-ko.ts
> +    번역("1100C", ".menu > a", [[/Blocked users/, "차단된 유저"]]),
```suggestion
    번역("1100C", ".menu > a", [[/Blocked users/, "차단된 사용자"]]),
```

2021-08-09 05:08 UTC, hsh2001 commented on chrome/github-ko.ts
> +    번역("1300D", ".SelectMenu-modal span", [[/Select type/, "타입 선택"], [/Select language/, "언어 선택하기"]]),
```suggestion
    번역("1300D", ".SelectMenu-modal span", [[/Select type/, "타입 선택하기"], [/Select language/, "언어 선택하기"]]),
```

통일성을 위해 둘 다 '선택하기'로 하는 것이 좋을 것 같습니다!

2021-08-10 10:32 UTC, hatemogi requested changes
번역 작업을 해주셔서 감사합니다! 제 의견을 조금씩 달아보았는데요, 한번 검토해주시면 감사하겠습니다. 혹시 제 의견대로, 또는 3안으로, (아니면 원안대로) 반영해주시면, 또 볼게요.

번역 자체가 워낙 어려운 일이기도 하고, 또 저도 번역 전문가가 아니다 보니 의견이 다를 수 있으니, 어느게 낫다고 주장하기는 어려울 것 같습니다. 그저 의견이니 참고 부탁드려요.

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +                                        [/Your codespaces/, "내 코드스페이스"],
👍

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("0400L", ".dashboard-feed", [[/introduece yourself/, "자기소개를 해보세요"]]),
introduece는 오타일까요?

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1100E", ".col-md-9.col-12 h2", [[/Public profile/, "공개 프로필"], [/Change username/, "계정명 변경"], [/Export account data/, "계정 데이터 내보내기"], [/Successor settings/, "후속 설정"], [/Theme preferences/, "선호
"테마 선택"이나 "테마 설정" 정도의 번역은 어떠실까요?

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1100E", ".col-md-9.col-12 h2", [[/Public profile/, "공개 프로필"], [/Change username/, "계정명 변경"], [/Export account data/, "계정 데이터 내보내기"], [/Successor settings/, "후속 설정"], [/Theme preferences/, "선호
저에게는 username을 "계정명"으로 번역하기에는 조금 어색한데요, 혹시 다른 단어로 고려해보신 거 있으실까요?

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1100I", ".col-md-9.col-12 p", [[/Looking to manage account security settings/, "계정 보안 설정을 관리하는 법을 찾고 계신가요?"], [/Export all repositories and profile metadata for/, "다음 계정에 대한 모든 저장소와 메타데이터를 내보
"~에 대한" 보다 "다음 계정에 있는"라고 번역은 어떠실까요?

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    , [/Choose how GitHub looks to you. Select a single theme, or sync with your system and automatically switch between day and night themes./, "GitHub의 테마를 선택해주세요. 하나의 테마를 선택하거나 시스템과 동기화하여 낮/밤 테마를
* "하나의 테마를 선택하거나" -> "테마 하나를 선택하거나"
* "자동 전환하도록 할 수 있습니다" -> "자동 전환할 수 있습니다"

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1100J", ".col-md-9.col-12 span", [[/GitHub theme will match your system active settings/, "깃허브 테마를 당신의 시스템 상태에 맞춰 변경되도록 합니다"]]),
* "시스템 상태에 맞춰 변경되도록 합니다" -> "시스템 상태에 맞춰 변경합니다"

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200A", ".container-lg.mx-auto.p-responsive a", [[/Explore/, "탐색"], [/Topics/, "주제"], [/Trending/, "트렌드"], [/Collections/, "컬렉션"], [/Events/, "이벤트"], [/GitHub Sponsors/, "깃허브 스폰서"], [/Get ema
혹시 이부분은 "이메일 주소를 업데이트"하는 게 아니라, "이메일로 소식을 받는"기능일까요?

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200D", ".Box-header.d-flex a", [[/Trending repositories/, "뜨고있는 저장소들"], [/Trending developers/, "뜨고있는 개발자들"]]),
뜨고있는 -> 뜨고 있는

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200B", ".border-top.px-3 a", [[/starred topics/, "스타받은 토픽"]]),
스타받은 -> 스타 받은

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200F", ".border.my-4 h2", [[/Based on repositories you’ve viewed/, "관심사에 맞는 저장소 추천입니다"]]),
아마도 실제로 방문(view)했던 저장소를 기준으로 추천한 것 같아요. 관심사랑도 대략 일치할 것 같습니다만...

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200G", ".border-top.p-3 a", [[/See more matching repositories/, "다른 추천 저장소 보기"]]),
"더 많은 추천 저장소"

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200I", ".Box-footer a", [[/See more trending repositories/, "뜨고있는 저장소들 더보기"], [/See more trending developers/, "뜨고있는 개발자들 더보기"]]),
뜨고있는 -> 뜨고 있는

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200J", ".col-md-8.col-lg-6.py-4 span a", [[/get email updates/, "이메일 업데이트를 받아보세요"]]),
이메일로 소식을 받아보세요

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1300C", ".mt-4 h2", [[/Popular repositories/, "인기있는 저장소들"]]),
인기있는 -> 인기 있는

2021-08-10 10:32 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1300D", ".SelectMenu-modal span", [[/Select type/, "타입 선택"], [/Select language/, "언어 선택하기"]]),
또는 둘다 "선택"도 좋을 것 같습니다.

2021-08-10 13:00 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("0400L", ".dashboard-feed", [[/introduece yourself/, "자기소개를 해보세요"]]),
앗. 수정중에 오타가 있었고 그게 그대로 반영된 것 같습니다! 놓쳤던 부분인데 확인 감사드립니다!

2021-08-10 13:03 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1100E", ".col-md-9.col-12 h2", [[/Public profile/, "공개 프로필"], [/Change username/, "계정명 변경"], [/Export account data/, "계정 데이터 내보내기"], [/Successor settings/, "후속 설정"], [/Theme preferences/, "선호
Theme Preferences는 원문에 있는 preference에 충실하게 번역을 해보았는데, 실제 사용때는 테마 설정이 조금더 어울리는 느낌이 듭니다!

username을 '유저명'으로 처음에 번역했었는데, Change username에 해당되는 부분이 계정 자체의 닉네임을 의미하는 것 같아서 계정명 변경으로 번역했었습니다. 다른 단어를 선택하셔도 괜찮은게 저도 보기에 어색했지만 마땅히 떠오르는게 없었습니다..

2021-08-10 13:05 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1100I", ".col-md-9.col-12 p", [[/Looking to manage account security settings/, "계정 보안 설정을 관리하는 법을 찾고 계신가요?"], [/Export all repositories and profile metadata for/, "다음 계정에 대한 모든 저장소와 메타데이터를 내보
'계정에 해당되는'의 느낌으로 해석했었는데, 수정하고나니 번역투의 느낌이 강하게 느껴져서 '계정에 대한'으로 수정했던 내용입니다!  말씀해주신대로 '계정에 있는' 이 조금더 함축적 의미를 잘 나타내는 느낌이 들어서 좋을 것 같습니다!

2021-08-10 13:06 UTC, mandoopapa commented on chrome/github-ko.ts
> +    , [/Choose how GitHub looks to you. Select a single theme, or sync with your system and automatically switch between day and night themes./, "GitHub의 테마를 선택해주세요. 하나의 테마를 선택하거나 시스템과 동기화하여 낮/밤 테마를
번역 내용이 매끄럽지 못했습니다! 수정 감사드립니다.

2021-08-10 13:07 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1100J", ".col-md-9.col-12 span", [[/GitHub theme will match your system active settings/, "깃허브 테마를 당신의 시스템 상태에 맞춰 변경되도록 합니다"]]),
자연스러운 번역 내용으로 보입니다! 감사합니다

2021-08-10 13:09 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1200A", ".container-lg.mx-auto.p-responsive a", [[/Explore/, "탐색"], [/Topics/, "주제"], [/Trending/, "트렌드"], [/Collections/, "컬렉션"], [/Events/, "이벤트"], [/GitHub Sponsors/, "깃허브 스폰서"], [/Get ema
Get email updates가 해당 이메일로 뉴스레터를 전달받는 주기를 설정하는 내용으로, '이메일 뉴스레터 받기 설정' 등으로 처음에 고려해봤으나 매끄러운 번역을 찾지 못해 있는 그대로 번역을 해둔 부분이었습니다. 사실 간편하고 함축적으로 번역할 수 있는 내용이 아직 딱 떠오르지 않습니다 ㅠㅠ

2021-08-10 13:10 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1200B", ".border-top.px-3 a", [[/starred topics/, "스타받은 토픽"]]),
위의 뜨고 있는, 스타 받은 과같은 띄어쓰기 부분은 붙여쓰는 것이 좋지 않을까라는 개인적인 생각입니다만, 띄워쓴 상태로 테스트해보면 조금 더 깔끔한 느낌이 듭니다

2021-08-10 13:12 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1200F", ".border.my-4 h2", [[/Based on repositories you’ve viewed/, "관심사에 맞는 저장소 추천입니다"]]),
약간의 초월번역 느낌으로 번역해본 부분입니다. 저에게 뜬 추천 repo들이 저의 관심사(interests)를 기반으로 한 것인가라는 생각에 위의 번역과 함께 같은 맥락으로 수정했는데, 사실 겹치는 내용이 아니라 '방문했던 저장소 기준 추천'이 의미상 더 적합할 것 같습니다!

2021-08-10 13:13 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1200G", ".border-top.p-3 a", [[/See more matching repositories/, "다른 추천 저장소 보기"]]),
앗... 감사합니다!

2021-08-10 13:15 UTC, mandoopapa commented on chrome/github-ko.ts
> +    번역("1300D", ".SelectMenu-modal span", [[/Select type/, "타입 선택"], [/Select language/, "언어 선택하기"]]),
Select type과 Select Language 모두 선택으로 통일하면 깔끔할 듯 합니다!

2021-08-10 13:28 UTC, mandoopapa commented on chrome/github-ko.ts
> +                                        [/Your codespaces/, "내 코드스페이스"],
저에게는 처음해보는 작업이라 부족함이 많습니다. 많은 부분 꼼꼼하게 살펴봐주시고 의견을 주셔서 진심으로, 너무나도 감사드립니다.

2021-08-14 15:44 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1100E", ".col-md-9.col-12 h2", [[/Public profile/, "공개 프로필"], [/Change username/, "계정명 변경"], [/Export account data/, "계정 데이터 내보내기"], [/Successor settings/, "후속 설정"], [/Theme preferences/, "선호
그렇네요...username 번역이 마땅치 않네요... 우선 "계정명"으로 하면 좋겠습니다.

2021-08-14 15:44 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200A", ".container-lg.mx-auto.p-responsive a", [[/Explore/, "탐색"], [/Topics/, "주제"], [/Trending/, "트렌드"], [/Collections/, "컬렉션"], [/Events/, "이벤트"], [/GitHub Sponsors/, "깃허브 스폰서"], [/Get ema
그렇다면, "이메일 뉴스레터 설정"로 어떨까요?

2021-08-14 15:44 UTC, hatemogi commented on chrome/github-ko.ts
> +    번역("1200B", ".border-top.px-3 a", [[/starred topics/, "스타받은 토픽"]]),
띄어쓰기는 느낌의 문제가 아니라 문법의 문제이니까, 오히려 결정이 쉬운 것 같습니다. 기준으로 삼는 사전에 한 단어로 등재되어 있으면, 붙여서 쓰면 되고, 아니라면 띄어쓰면 되는 것인데요, 아직 "스타받다"라는 단어가 어떤 기준의 사전에 등재될 만한 하나의 단어로 보기는 어려운 것 같습니다.

2021-08-16 12:36 UTC, hatemogi approved these changes
훌륭한 작업 감사드립니다!

2021-08-16 12:37 UTC, merged

2021-08-16 13:16 UTC, mandoopapa commented
멋진 프로젝트 생성과 참여를 허락해주심에 모두 감사드립니다!